# Generated by Django 4.2.2 on 2023-07-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_logs', '0002_post_delete_blogtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
